### ISSUE TITLE
'View only' Mode for pd-input & pd-textarea

### ISSUE THREAD

**Issue by thomasschneiter** [Lambda-IT/parlamentsdienste-components#179]
Copy&Paste from Mail:

Read only vs. View only
Kein Problem, dann belassen wir die Benennung bei Read only und View only, wie von euch eingangs vorgeschlagen.
@Thomas würdest du diese beiden States im Storybook aktualisieren, resp. hinzufügen?
https://xd.adobe.com/view/4b788182-140b-46ff-46f5-3c623cf5b5b3-3d49/screen/e8bea3cb-bc99-4c3d-8053-053412dd7607/specs/

**Comment by thomasschneiter** [comment]
@CuriaPLUS I don't think that a "view only" mode should be added to the component.
There is no native attribute for this in `<input>` and it's not an input anymore. In the dom this should be just a `<p>` and not an `<input>`, otherwise a screenreader will read this as a form input when it's actually just some text.

I'd suggest that if you do a view mode you exchange all the input components with just text.

**Comment by CuriaPLUS** [comment]
Some context why we need this type of input / text:
We have forms that are viewed by different user types. Some users have the right to edit this specific form - others do not. The accessed form stays the same.
**If a user has edit rights:** the form is displayed with read only fields and an edit button. By clicking on the edit button the input fields change to an edit-state.
> For this user the form is displayed in a **read only mode**  and in an **edit mode**.

The same form can also be accessed by another user type.
This user doesn't have the right to edit anything. It's just information.
The results of a recent usability test have shown that users were looking for an edit button because the form looks editable (read-only inputs). As they are not allowed to edit we decided to show the form in a **new state called "view only"**.
> It is much easier for us to only change the property instead of creating a new page which needs to be reachable from everywhere.
Also, these forms are only shown when we need it specifically for these different user types.

Depending on the user role it's important to display the form accordingly.

**Comment by thomasschneiter** [comment]
I'll add a view-only Mode that replaces the `input` with a `p`. It will use the same paddings as the input (padding+border). 
So the result will look similar to the input but without the border and input functionality

**Comment by MadeleineMatter** [comment]
https://xd.adobe.com/view/4b788182-140b-46ff-46f5-3c623cf5b5b3-3d49/screen/b6fece0c-38e1-4f10-8a12-6ea08d2a05f1/specs/
