### ISSUE TITLE
PdListItem / PdListItemExpandable --> Overlay

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#220]
We had this issue in the past: https://github.com/Lambda-IT/parlamentsdienste-components/issues/84

And I might have found a solution for it with CSS. Would it be possible to add **overflow: visible** to those Components?

The issue happens not only with Menus but also with Dropdown/Combobox if the list is to small to show the Dropdown-Content and this would actually solve a lot of UX issues.

Could you look at this until the end of January? If this Solution works for you as well that would be awesome!

For now I fixed this on our side by overwriting the styles for those components

```
pd-panel-content,
pd-list-item,
pd-list-item-expandable {
  overflow: visible;
}
```

**Comment by tom-wenger** [comment]
We did a research on this issue and we might have found a solution.
The thing is, that all the Popup-Components (Dropdown, Combobox, Datepicker) are cut off because the parent (the pd-panel or pd-list) have overflow: hidden. We cannot give these elements an overflow:visible because then long texts would overflow the element.
The only good solution to this problem is to take the Popup-Part of the Component (the List of the Dropdown) and move it away from his origin place in the dom-tree and attach it to the body.
Its a bigger modification, we could do it for the combobox probably till end of january. Then you could test it and when its the right way we would implement it for the other popup-components too.
what do you think?

**Comment by CuriaPLUS** [comment]
As we fixed this for now on our side we don't think this is as HighPrio anymore so I will remove the label.

**Comment by tom-wenger** [comment]
i'll close this for now. if the problem shows up again we can reopen it.
