### ISSUE TITLE
PdTable Events for Pagination, Filtering and Sorting

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#235]
Within the Curiaplus Application we have large datastructures which are displayed in PdTable Components. To keep the data load on Frontend Site as small as possible we support Pagination, Filtering and Sorting on our endpoints.

It would be great to have some additional events to detect a User interaction regarding all this topics (Pagination, filtering, sorting) so we could trigger our Backend Service with the corresponding parameters. Also a new mode would be needed so that the PdTable knows if it should do the action by itself or just trigger those events (it's handled by the endpoint) and a new set of data is provided via databinding.

**Possible Events can be:**

- pd-sort -> provides the column name and the current order
- pd-filter-input -> provides the column name and the filtered value on keyboard input
- pd-filter-change -> provides the coumn name and the filtered value

**Possible Properties can be:**

- externalRowHandling -> Adds above described Events and custom pagination handling (see below)

**Possible solution for Pagination could be:** 

1. Either use a own pagination component underneath the table by convention
2. Provide a slot for a PdPagination Component
3. Or allow a prop and event mapping for the internal used pagination component: 
        - paginationConfig = {...paginationProps}
        - And a seperate Mapping for the PdPagination Events

**Comment by tom-wenger** [comment]
Ok, this seems clear.
We'll implement an externalRowHandling property who disables the internal functionality for filtering, sorting and pagination and activates the outgoing events pd-sort, pd-filter-input and pd-filter-change as you described it above.
For the pagination we would provide a slot for a PdPagination component, that seems the best way.

One more thing to consider:
The functionality of the checkbox on top to select/disselect all items or who shows the indeterminate status when a least one item is selected but not all will also be disabled. The existing outgoing pd-selected event of that checkbox will remain the same but then there will be a selected-status property who takes the values 'all' | 'none' | 'indeterminate' and it needs to be handled also from outside.
For example: If there's an item selected on page 2, this property needs to be set on indeterminate since the component doesn't know about items on page 2.
is that alright?

**Comment by tom-wenger** [comment]
This feat. is now available in the release 2.6.6. See the changelog and the storyboard for further information.
