### ISSUE TITLE
Table multiselect

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#37]
When selecting multiple rows in the table the "header-select" should also change its state (see image below).
It is especially needed in case the user goes to the next page: The state in the "header-select" indicates that the rows on previous pages are still selected.
![image](https://user-images.githubusercontent.com/77280472/115272244-79e49580-a13e-11eb-9f06-e4f5e992799f.png)

**Comment by thomasschneiter** [comment]
@CuriaPLUS Since paging is done outside of the table component, it doesn't know if there are rows selected on another page. I could maybe add a property that indicates if there are rows selected outside of the current table (with value "all/some/none" for example).

 Or do you already have an idea how that should work in your case?

**Comment by CuriaPLUS** [comment]
The rows could have a fixed property 'selected', the list used for pagination is a subset of the complete list (rows) of the data. Maybe something in this direction?
