### ISSUE TITLE
Styling of chips don't match Styleguide

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#39]
Styling of Chips don't match [XD-Styleguide](https://xd.adobe.com/view/727dd55b-1491-4151-8f5d-db8600161be8-272e/screen/9f1e1071-2d1c-4045-bf89-39a96b62da1b/specs/) in the following points:

**General:**
* size height: `32 px`
* background-colour of disabled state shoud be `#BABABA` (Grey 6)
* background-colour of default (enabled) state should be `#E3E0E0` (Bon Jour) instead of `#dee2e6`
* font-colour should be `#033840` (Blue Whale)

**Toggle / Input Chips:**
* colour of selected chip should be `#66D9E8` (Cyan 3) instead of `#0b7285`

**Choice Chips**
* colour of activated chip should be `#66D9E8` (Cyan 3) instead of `#0b7285`

**Comment by matthiasbaldi** [comment]
Discussion is running with Designsensor (Tinu) - because some colors are inconsistent between the color board and each component.

Example:
https://xd.adobe.com/view/727dd55b-1491-4151-8f5d-db8600161be8-272e/screen/9f1e1071-2d1c-4045-bf89-39a96b62da1b/specs/
https://xd.adobe.com/view/727dd55b-1491-4151-8f5d-db8600161be8-272e/screen/7466b311-e8ae-4e89-83ad-b6e6c4ec8d50/specs/

PR open for the other issues: #50
