### ISSUE TITLE
Question: Tooltips / Popover Interaction

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#60]
Hi there,
we have an issue implementig Tippy as specified in StoryBook:
https://parlamentsdienstecore.lambda-it.ch/?path=/story/interactions-tooltip-popover--popover

I currently see two options:
- the PD component libarary provides either a custom element or a directive/custom attribute in Stencil for a tool tip
- all project that use the popover have to wrap (resp. use a wrapped version of) tippy but the integration would differ a little each time

Are there other options which we missed and would facilitate the integration?

**Comment by CuriaPLUS** [comment]
In the example tippy V6 is used, we have found the `vue-tippy` library that adds a wrapper for vue. The problem is that the version 4 is used, in the @next version tippy V6 would be used but has the requirement for Vue.js 3. So we can not use that at the moment.

Another option would be to use the default tooltips from bootstrap: https://getbootstrap.com/docs/4.4/components/tooltips/ which need to be initialised manually.

**Comment by thomasschneiter** [comment]
There is no possiblility to create a webcomponent that can be used as an attribute of an element. The browser API doesn't support that. Since a tooltip needs to be attached to elements and have a relative position to it, it doesn't make sense to create a custom element for that. A tooltip needs to be an attribute to be able to use it properly.

The only useful thing we can do is to provide a styling for a specific implementation which in our case is tippy.
If you can't use this specific implementation, I'd suggest you use a vue.js specific tooltip library and recreate the styling from the design system.

Bootstrap uses JQuery for the tooltip functionality which isn't used in most frameworks anymore. That's why we used tippy as a suggested library.

**Comment by matthiasbaldi** [comment]
@CuriaPLUS Please reopen it again, if you have further feedback.
