### ISSUE TITLE
Custom Colors

### ISSUE THREAD

**Issue by jwanner83** [Lambda-IT/parlamentsdienste-components#73]
I'm currently working on a project from the Parlamentsdienste, which has a slightly different design than this component library - the colors in particular. I was wondering if it would be possible to enable the change of colors with CSS vars as you did with, for example, paddings on Buttons `var(--pd-button-right-radius, 0.25rem)` etc. What do you guys think about this?

**Comment by matthiasbaldi** [comment]
The reason for the parlamentsdienste-components was that we had a design for all Parlamentsdienst-applications.
So it is as it should be. According our design it should not be possible to change button radius for example.
Otherwise you have to talk to Jürg Kurt (Parlamentsdienste) to speak about the design and if we have to adapt some more stuff.
Please contact Jürg to discuss this topic.
