### ISSUE TITLE
PD-Panel

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#84]
When working with a Panel with small content and the content contains a pd-menu the menu is cutoff.
Either the Menu should overlap or the panel should grow bigger if the menu is shown. This might be a hard fix but rather important for a good UX

![Screenshot 2021-09-23 at 14 55 55](https://user-images.githubusercontent.com/77280472/134510553-c253d744-be8d-44d0-88ae-fc577b790e64.png)
![Screenshot 2021-09-23 at 14 56 00](https://user-images.githubusercontent.com/77280472/134510550-00439617-629d-4e31-a664-eb48d5a1f24d.png)

**Comment by matthiasbaldi** [comment]
Ya, that is true. Is this for a mobile mode or how large is the screen in this case? Just to have an orientation what we have to test.

**Comment by CuriaPLUS** [comment]
Its with nested PD-Panels meaning its similar to the example page:

<img width="1710" alt="Screenshot 2021-09-24 at 09 07 49" src="https://user-images.githubusercontent.com/77280472/134632911-9cec4dea-f0e8-42e8-a24c-2882ae8a0788.png">

**Comment by matthiasbaldi** [comment]
We discussed this issue internally and we think that it is not solvable within our web components.
The problem is, that we can not attach the menu content to the body tag as you would do it i.e. in plain Angular or Vue because it is wrapped into the web component and shadow dom.
In this particular case the menu structure is absolute to the menu component itself. This means that the opened menu will be always within the panel component. When you would change the overflow behavior of the parent container (in this case the panel) there would be a vertical scrollbar.

A solution would be that you implement the menu for this case based on the components we have (pd-menu-item, pd-icon, etc.) and you attach it yourself to the body. Then it would be able to floating above the panel component. You could use a portal concept as we Angular uses i.e. in Angular Material.

**Comment by CuriaPLUS** [comment]
We "fixed" this by setting the pd-panel-content to min-height: 150px;
